
@base = https://localhost:7113
@id = 
// colar acima o id gerado em "cadastrar"

### Cadastrar
POST {{base}}/api/v1/usuarios
Content-Type: application/json

{
  "nome": "Ricardo",
  "email": "ricardo@gmail.com",
  "senha": "12345678",
  "cargo": "Dev"
}

### Listar todos
GET {{base}}/api/v1/usuarios

### Buscar por id
GET {{base}}/api/v1/usuarios/{{id}}

### Atualizar
PUT {{base}}/api/v1/usuarios/{{id}}
Content-Type: application/json

{
  "nome": "Ricardo Nocais",
  "cargo": "Desenvolvedor"
}

### Desativar
DELETE {{base}}/api/v1/usuarios/{{id}}

### Ativar
POST {{base}}/api/v1/usuarios/{{id}}/ativar

### Cadastrar email duplicado
POST {{base}}/api/v1/usuarios
Content-Type: application/json

{
  "nome": "Ronaldo",
  "email": "ricardo@gmail.com",
  "senha": "senha",
  "cargo": "Supervisor"
}